services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orbi
    ports:
      - "5432:5432"
    volumes:
      - orbi_pg:/var/lib/postgresql/data

volumes:
  orbi_pg:
